<a href="https://colab.research.google.com/github/hugomorpar/Practicas_Clases/blob/main/M2_Procesamiento_de_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Modulo 2

## Introduccion a Numpy

In [1]:
import numpy as np

In [2]:
# crea array

xs = np.array([3, 1, 2])
print(xs)

[3 1 2]


In [3]:
# array o vector unidimensional (unalista dentro del metodo n.array())

my_vector = np.array(['este', 'es', 'un', 'vector'])
print(my_vector)

['este' 'es' 'un' 'vector']


In [4]:
# matriz, array bidimensional (una lista de listas dentro del metodo n.array())

my_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(my_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# arreglos (array)

arreglo_1 = np.array([3, 1, 2])
arreglo_2 = np.array([3, 'hola', 2])
arreglo_3 = np.array([3, 21, 1, 2])

print(arreglo_1)
print(arreglo_2)
print(arreglo_3)

[3 1 2]
['3' 'hola' '2']
[ 3 21  1  2]


In [6]:
# array de 0 con dimension 5

a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [7]:
# array de 1 con dimension 5

b = np.ones(2)
print(a)

[0. 0. 0. 0. 0.]


In [8]:
# array full (dimension, valor)

c = np.full(2, 7)
print(c)

[7 7]


In [9]:
# array random (dimension, random)

d = np.random.random(5)
print(d)

[0.51415469 0.56798602 0.80304392 0.91827784 0.08487689]


In [10]:
# atributos del arreglo

# array de 1 dimension, valores de 0 a 9, 5 datos
x = np.random.randint(10, size=5)
print(x)
print("x ndim:", x.ndim)
print("x shape:", x.shape)
print("x size:", x.size)
print("x dtype", x.dtype)

[4 5 3 1 3]
x ndim: 1
x shape: (5,)
x size: 5
x dtype int64


In [11]:
# indexacion de arreglos. print(x[ubicacion])

print(x)

print(x[0])
print(x[4])
print(x[-1])
print(x[-2])

[4 5 3 1 3]
4
3
3
1


In [12]:
# segmentacion de arreglos
# parte desde cero y corta en n-1

# array de 1 dimension, valores de 0 a 9, 8 datos
x1 = np.random.randint(10, size=8)
print(x1)

print(x1[3:])  # array desde la ubicacion 3

print(x1[:3])  # array hasta la ubicacion 3

print(x1[2:4])  # array desde la ubicacion 2 hasta la 4

[4 5 6 2 9 6 7 5]
[2 9 6 7 5]
[4 5 6]
[6 2]


In [13]:
# segmentacion de arreglos
# parte desde cero y corta en n-1

# array de 1 dimension, valores de 0 a 9, 8 datos
y = np.random.randint(10, size=8)
print(y)

y1 = y[0:2]  # nuevo array desde la ubicacion 0 a 2
print(y1)

y1[0] = 12  # cambia valor de ubicacion 0 por 12
print(y1)

print(y)  # tambien afecta al array original

[0 9 2 3 4 0 8 6]
[0 9]
[12  9]
[12  9  2  3  4  0  8  6]


In [14]:
# segmentacion de arreglos
# parte desde cero y corta en n-1

# array de 1 dimension, valores de 0 a 9, 8 datos
y = np.random.randint(10, size=8)
print(y)

y1 = y[0:2].copy()  # COPIA array y en y1 desde la ubicacion 0 a 2
print(y1)

y1[0] = 12  # cambia valor de ubicacion 0 por 12
print(y1)

print(y)  # NO afecta al array original

[7 0 9 2 4 2 5 5]
[7 0]
[12  0]
[7 0 9 2 4 2 5 5]


In [15]:
# concatenacion de arreglos

x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [16]:
# division de arreglos

x = np.array([1, 2, 3, 99, 99, 3, 2, 1])
print(x)
# divide array x en x1(0-3),x2(3-5),x3(resto).
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[ 1  2  3 99 99  3  2  1]
[1 2 3] [99 99] [3 2 1]


In [17]:
# agregar elementos al array

a = np.array([1, 2, 3, 4, 5, 6])
print(a)

b = np.append(a, [7])  # agregar valor 7 al array a
print(b)

[1 2 3 4 5 6]
[1 2 3 4 5 6 7]


## Aritmetica de arreglos (array)

In [18]:
# operaciones aritmeticas comunes

x = np.random.randint(1, 8, size=4)  # 1 a 8, 5 datos

print("x =", x)
print("x+5=", x+5)  # suma 5 a cada elemento del arreglo
print("x-5=", x-5)  # resta 5 a cada elemento del arreglo
print("x*2=", x*5)  # multiplica por 2 cada elemento del arreglo
print("x/2=", x/5)  # divide por 2 cada elemento del arreglo
print("x//2=", x//5)  # resto de la division por 2 de cada elemento del arreglo

x = [3 7 5 4]
x+5= [ 8 12 10  9]
x-5= [-2  2  0 -1]
x*2= [15 35 25 20]
x/2= [0.6 1.4 1.  0.8]
x//2= [0 1 1 0]


In [19]:
# valor absoluto

y = np.array([-1, 2, -3, 4, -5, 6])

print(y)
print(np.absolute(y))
print(np.abs(y))

[-1  2 -3  4 -5  6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [20]:
# funciones trigonometricas

# matriz N-dimensional de números espaciados uniformemente. inicia en 0, termina en pi, 3 elementos
theta = np.linspace(0, np.pi, 3)

print("theta=", theta)
print("sin=", np.sin(theta))
print("cos=", np.cos(theta))
print("tan=", np.tan(theta))

theta= [0.         1.57079633 3.14159265]
sin= [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos= [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan= [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [21]:
# # funciones trigonometricas inversas

x = np.array([-1, 0, 1])

print("x=", x)
print("arcsin=", np.arcsin(x))
print("arccos=", np.arccos(x))
print("arctan=", np.arctan(x))

x= [-1  0  1]
arcsin= [-1.57079633  0.          1.57079633]
arccos= [3.14159265 1.57079633 0.        ]
arctan= [-0.78539816  0.          0.78539816]


In [22]:
# exponente (base, exponente)

x = np.array([1, 2, 3])

print("x=", x)
print("2^x=", np.power(2, x))
print("x^2=", np.power(x, 2))

x= [1 2 3]
2^x= [2 4 8]
x^2= [1 4 9]


In [23]:
# logaritmos

x = np.array([1, 2, 4, 10])

print(x)
print("ln(x)=", np.log(x))  # base 1
print("log2(x)=", np.log2(x))  # base 2
print("log10(x)=", np.log10(x))  # base 10

[ 1  2  4 10]
ln(x)= [0.         0.69314718 1.38629436 2.30258509]
log2(x)= [0.         1.         2.         3.32192809]
log10(x)= [0.         0.30103    0.60205999 1.        ]


In [24]:
# agregaciones

x = np.array([1, 5, 2, 6, 3])

print(x)
print("minimo=", np.min(x))
print("maximo=", np.max(x))
print("mediana=", np.median(x))
print("media=", np.mean(x))
print("suma=", np.sum(x))

[1 5 2 6 3]
minimo= 1
maximo= 6
mediana= 3.0
media= 3.4
suma= 17


## Introduccion a Pandas

### series, dataframes e indices

In [25]:
import pandas as pd

### Series

In [26]:
# matriz unidimensional de datos, indexada
data = pd.Series([0.25, 0.5, 0.75, 1.0])
print(data)

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64


In [27]:
data.values  # los valores son simplemente un array

array([0.25, 0.5 , 0.75, 1.  ])

In [28]:
# acceso a indice especifico

print(data[2])
print(data[1:3])

0.75
1    0.50
2    0.75
dtype: float64


In [29]:
# serie como matriz Numpy generalizada

data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
print(data)

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64


In [30]:
# serie como un diccionario especializado

population_dict = {'California': 38332521, 'Texas': 26448193,
                   'New York': 19651127, 'Florida': 19552860, 'Illinois': 12882135}
population = pd.Series(population_dict)
print(population)

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64


### DataFrame
###matriz (array bidimensional etiquetada)

In [31]:
# construir la Serie diccionario

area_dict = {'California': 423967, 'Texas': 695662,
             'New York': 141297, 'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
print(area)

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64


In [32]:
# DataFrame: con el diccionario construido se genera un objeto de 2 dimensiones con etiquetas 'population' y 'area'
# Serie 'population' + Serie 'area'

states = pd.DataFrame({'population': population, 'area': area})
print(states)

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995


In [33]:
# index y columns
# acceso a los valores

print(states.index)
print(states.columns)

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')
Index(['population', 'area'], dtype='object')


### indices

In [34]:
# se operan igual que un array, no se pueden modificar, solo indican ubicacion.

ind = pd.Index([2, 3, 5, 7, 11])
print(ind)

Index([2, 3, 5, 7, 11], dtype='int64')
