<a href="https://colab.research.google.com/github/hugomorpar/Practicas_Clases/blob/main/Modulos_Procesamiento_de_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Modulo 2

## Introduccion a Numpy

In [88]:
import numpy as np

In [89]:
# crea array

xs=np.array([3,1,2])
print(xs)

[3 1 2]


In [90]:
# array o vector unidimensional (unalista dentro del metodo n.array())

my_vector=np.array(['este', 'es', 'un', 'vector'])
print(my_vector)

['este' 'es' 'un' 'vector']


In [91]:
# matriz, array bidimensional (una lista de listas dentro del metodo n.array())

my_matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(my_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [92]:
# arreglos (array)

arreglo_1=np.array([3,1,2])
arreglo_2=np.array([3, 'hola', 2])
arreglo_3=np.array([3,21,1,2])

print(arreglo_1)
print(arreglo_2)
print(arreglo_3)

[3 1 2]
['3' 'hola' '2']
[ 3 21  1  2]


In [93]:
# array de 0 con dimension 5

a=np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [94]:
# array de 1 con dimension 5

b=np.ones(2)
print(a)

[0. 0. 0. 0. 0.]


In [95]:
# array full (dimension, valor)

c=np.full(2, 7)
print(c)

[7 7]


In [96]:
# array random (dimension, random)

d=np.random.random(5)
print(d)

[0.48470376 0.92820467 0.36033542 0.06500176 0.10722757]


In [97]:
# atributos del arreglo

x=np.random.randint(10, size=5) #array de 1 dimension, valores de 0 a 9, 5 datos
print(x)
print("x ndim:", x.ndim)
print("x shape:", x.shape)
print("x size:", x.size)
print("x dtype", x.dtype)

[1 0 3 8 8]
x ndim: 1
x shape: (5,)
x size: 5
x dtype int64


In [98]:
# indexacion de arreglos. print(x[ubicacion])

print(x)

print(x[0])
print(x[4])
print(x[-1])
print(x[-2])

[1 0 3 8 8]
1
8
8
8


In [99]:
# segmentacion de arreglos
# parte desde cero y corta en n-1

x1=np.random.randint(10, size=8) #array de 1 dimension, valores de 0 a 9, 8 datos
print(x1)

print(x1[3:]) #array desde la ubicacion 3

print(x1[:3]) #array hasta la ubicacion 3

print(x1[2:4]) #array desde la ubicacion 2 hasta la 4

[0 8 4 7 3 1 7 7]
[7 3 1 7 7]
[0 8 4]
[4 7]


In [100]:
# segmentacion de arreglos
# parte desde cero y corta en n-1

y=np.random.randint(10, size=8) #array de 1 dimension, valores de 0 a 9, 8 datos
print(y)

y1=y[0:2] # nuevo array desde la ubicacion 0 a 2
print(y1)

y1[0]=12 # cambia valor de ubicacion 0 por 12
print(y1)

print(y) # tambien afecta al array original

[4 8 5 6 7 9 2 1]
[4 8]
[12  8]
[12  8  5  6  7  9  2  1]


In [101]:
# segmentacion de arreglos
# parte desde cero y corta en n-1

y=np.random.randint(10, size=8) #array de 1 dimension, valores de 0 a 9, 8 datos
print(y)

y1=y[0:2].copy() # COPIA array y en y1 desde la ubicacion 0 a 2
print(y1)

y1[0]=12 # cambia valor de ubicacion 0 por 12
print(y1)

print(y) # NO afecta al array original

[3 2 6 0 0 9 9 9]
[3 2]
[12  2]
[3 2 6 0 0 9 9 9]


In [104]:
# concatenacion de arreglos

x=np.array([1,2,3])
y=np.array([3,2,1])

np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [111]:
# division de arreglos

x=np.array([1,2,3,99,99,3,2,1])
print(x)
x1,x2,x3=np.split(x,[3,5]) # divide array x en x1(0-3),x2(3-5),x3(resto).
print(x1, x2, x3)

[ 1  2  3 99 99  3  2  1]
[1 2 3] [99 99] [3 2 1]


In [113]:
# agregar elementos al array

a=np.array([1,2,3,4,5,6])
print(a)

b=np.append(a,[7]) # agregar valor 7 al array a
print(b)

[1 2 3 4 5 6]
[1 2 3 4 5 6 7]


## Aritmetica de arreglos (array)